from src.ops.runtime.maintenance_readiness import (
    MaintenanceReadinessRequest as SectorAnalysisDailyReadinessRequest,
    MaintenanceReadinessResult as SectorAnalysisDailyReadinessResult,
)


SECTOR_ANALYSIS_DAILY_READY = "SECTOR_ANALYSIS_DAILY_READY"
SECTOR_ANALYSIS_DAILY_NON_TRADING_DAY = "SECTOR_ANALYSIS_DAILY_NON_TRADING_DAY"
SECTOR_ANALYSIS_DAILY_UPSTREAM_NOT_READY = "SECTOR_ANALYSIS_DAILY_UPSTREAM_NOT_READY"
SECTOR_ANALYSIS_DAILY_SOURCE_NOT_READY = "SA_DAILY_FACT_SOURCE_NOT_READY"
SECTOR_ANALYSIS_DAILY_PREVIEW_FAILED = "SA_DAILY_FACT_SOURCE_NOT_READY"
SECTOR_ANALYSIS_DAILY_SOURCE_TIMEOUT = "SA_DAILY_FACT_SOURCE_NOT_READY"
SECTOR_ANALYSIS_DAILY_ALREADY_ATTEMPTED = "SECTOR_ANALYSIS_DAILY_ALREADY_ATTEMPTED"


__all__ = [
    "SectorAnalysisDailyReadinessRequest",
    "SectorAnalysisDailyReadinessResult",
    "SECTOR_ANALYSIS_DAILY_READY",
    "SECTOR_ANALYSIS_DAILY_NON_TRADING_DAY",
    "SECTOR_ANALYSIS_DAILY_UPSTREAM_NOT_READY",
    "SECTOR_ANALYSIS_DAILY_SOURCE_NOT_READY",
    "SECTOR_ANALYSIS_DAILY_PREVIEW_FAILED",
    "SECTOR_ANALYSIS_DAILY_SOURCE_TIMEOUT",
    "SECTOR_ANALYSIS_DAILY_ALREADY_ATTEMPTED",
]
