from src.ops.runtime.maintenance_readiness import (
    MaintenanceReadinessRequest as HeatReadinessRequest,
    MaintenanceReadinessResult as HeatReadinessResult,
)


HEAT_READY = "HEAT_READY"
HEAT_NON_TRADING_DAY = "HEAT_NON_TRADING_DAY"
HEAT_UPSTREAM_NOT_READY = "HEAT_UPSTREAM_NOT_READY"
HEAT_SOURCE_NOT_READY = "HEAT_SOURCE_NOT_READY"
HEAT_PREVIEW_FAILED = "HEAT_PREVIEW_FAILED"
HEAT_AUTOMATION_SOURCE_TIMEOUT = "HEAT_AUTOMATION_SOURCE_TIMEOUT"
HEAT_AUTOMATION_ALREADY_ATTEMPTED = "HEAT_AUTOMATION_ALREADY_ATTEMPTED"


__all__ = [
    "HeatReadinessRequest",
    "HeatReadinessResult",
    "HEAT_READY",
    "HEAT_NON_TRADING_DAY",
    "HEAT_UPSTREAM_NOT_READY",
    "HEAT_SOURCE_NOT_READY",
    "HEAT_PREVIEW_FAILED",
    "HEAT_AUTOMATION_SOURCE_TIMEOUT",
    "HEAT_AUTOMATION_ALREADY_ATTEMPTED",
]
