STOCK_BASIC_FIELDS = [
    "ts_code",
    "symbol",
    "name",
    "area",
    "industry",
    "fullname",
    "enname",
    "cnspell",
    "market",
    "exchange",
    "curr_type",
    "list_status",
    "list_date",
    "delist_date",
    "is_hs",
    "act_name",
    "act_ent_type",
]

TRADE_CAL_FIELDS = ["exchange", "cal_date", "is_open", "pretrade_date"]
DAILY_FIELDS = ["ts_code", "trade_date", "open", "high", "low", "close", "pre_close", "change", "pct_chg", "vol", "amount"]
ADJ_FACTOR_FIELDS = ["ts_code", "trade_date", "adj_factor"]
DAILY_BASIC_FIELDS = [
    "ts_code",
    "trade_date",
    "close",
    "turnover_rate",
    "turnover_rate_f",
    "volume_ratio",
    "pe",
    "pe_ttm",
    "pb",
    "ps",
    "ps_ttm",
    "dv_ratio",
    "dv_ttm",
    "total_share",
    "float_share",
    "free_share",
    "total_mv",
    "circ_mv",
]
CYQ_PERF_FIELDS = [
    "ts_code",
    "trade_date",
    "his_low",
    "his_high",
    "cost_5pct",
    "cost_15pct",
    "cost_50pct",
    "cost_85pct",
    "cost_95pct",
    "weight_avg",
    "winner_rate",
]
MONEYFLOW_FIELDS = [
    "ts_code",
    "trade_date",
    "buy_sm_vol",
    "buy_sm_amount",
    "sell_sm_vol",
    "sell_sm_amount",
    "buy_md_vol",
    "buy_md_amount",
    "sell_md_vol",
    "sell_md_amount",
    "buy_lg_vol",
    "buy_lg_amount",
    "sell_lg_vol",
    "sell_lg_amount",
    "buy_elg_vol",
    "buy_elg_amount",
    "sell_elg_vol",
    "sell_elg_amount",
    "net_mf_vol",
    "net_mf_amount",
]
TOP_LIST_FIELDS = [
    "trade_date",
    "ts_code",
    "name",
    "close",
    "pct_change",
    "turnover_rate",
    "amount",
    "l_sell",
    "l_buy",
    "l_amount",
    "net_amount",
    "net_rate",
    "amount_rate",
    "float_values",
    "reason",
]
BLOCK_TRADE_FIELDS = ["ts_code", "trade_date", "price", "vol", "amount", "buyer", "seller"]
DIVIDEND_FIELDS = [
    "ts_code",
    "end_date",
    "ann_date",
    "div_proc",
    "stk_div",
    "stk_bo_rate",
    "stk_co_rate",
    "cash_div",
    "cash_div_tax",
    "record_date",
    "ex_date",
    "pay_date",
    "div_listdate",
    "imp_ann_date",
    "base_date",
    "base_share",
]
HOLDERNUMBER_FIELDS = ["ts_code", "ann_date", "end_date", "holder_num"]
LIMIT_LIST_FIELDS = [
    "trade_date",
    "ts_code",
    "industry",
    "name",
    "close",
    "pct_chg",
    "amount",
    "limit_amount",
    "float_mv",
    "total_mv",
    "turnover_ratio",
    "fd_amount",
    "first_time",
    "last_time",
    "open_times",
    "up_stat",
    "limit_times",
    "limit",
]
STK_LIMIT_FIELDS = [
    "trade_date",
    "ts_code",
    "pre_close",
    "up_limit",
    "down_limit",
]
MARGIN_FIELDS = [
    "trade_date",
    "exchange_id",
    "rzye",
    "rzmre",
    "rzche",
    "rqye",
    "rqmcl",
    "rzrqye",
    "rqyl",
]
SUSPEND_D_FIELDS = [
    "ts_code",
    "trade_date",
    "suspend_timing",
    "suspend_type",
]
STK_NINETURN_FIELDS = [
    "ts_code",
    "trade_date",
    "freq",
    "open",
    "high",
    "low",
    "close",
    "vol",
    "amount",
    "up_count",
    "down_count",
    "nine_up_turn",
    "nine_down_turn",
]
STOCK_ST_FIELDS = [
    "ts_code",
    "name",
    "trade_date",
    "type",
    "type_name",
]
LIMIT_LIST_THS_FIELDS = [
    "trade_date",
    "ts_code",
    "name",
    "price",
    "pct_chg",
    "open_num",
    "lu_desc",
    "limit_type",
    "tag",
    "status",
    "first_lu_time",
    "last_lu_time",
    "first_ld_time",
    "last_ld_time",
    "limit_order",
    "limit_amount",
    "turnover_rate",
    "free_float",
    "lu_limit_order",
    "limit_up_suc_rate",
    "turnover",
    "rise_rate",
    "sum_float",
    "market_type",
]
LIMIT_STEP_FIELDS = ["ts_code", "name", "trade_date", "nums"]
LIMIT_CPT_LIST_FIELDS = ["ts_code", "name", "trade_date", "days", "up_stat", "cons_nums", "up_nums", "pct_chg", "rank"]
FUND_DAILY_FIELDS = ["ts_code", "trade_date", "open", "high", "low", "close", "pre_close", "change", "pct_chg", "vol", "amount"]
INDEX_DAILY_FIELDS = ["ts_code", "trade_date", "open", "high", "low", "close", "pre_close", "change", "pct_chg", "vol", "amount"]

STK_PERIOD_BAR_FIELDS = [
    "ts_code",
    "trade_date",
    "end_date",
    "freq",
    "open",
    "high",
    "low",
    "close",
    "pre_close",
    "vol",
    "amount",
    "change",
    "pct_chg",
]

STK_PERIOD_BAR_ADJ_FIELDS = [
    "ts_code",
    "trade_date",
    "end_date",
    "freq",
    "open",
    "high",
    "low",
    "close",
    "pre_close",
    "open_qfq",
    "high_qfq",
    "low_qfq",
    "close_qfq",
    "open_hfq",
    "high_hfq",
    "low_hfq",
    "close_hfq",
    "vol",
    "amount",
    "change",
    "pct_chg",
]

INDEX_BASIC_FIELDS = [
    "ts_code",
    "name",
    "fullname",
    "market",
    "publisher",
    "index_type",
    "category",
    "base_date",
    "base_point",
    "list_date",
    "weight_rule",
    "desc",
    "exp_date",
]

INDEX_WEEKLY_FIELDS = ["ts_code", "trade_date", "close", "open", "high", "low", "pre_close", "change", "pct_chg", "vol", "amount"]
INDEX_MONTHLY_FIELDS = ["ts_code", "trade_date", "close", "open", "high", "low", "pre_close", "change", "pct_chg", "vol", "amount"]
INDEX_WEIGHT_FIELDS = ["index_code", "con_code", "trade_date", "weight"]
INDEX_DAILY_BASIC_FIELDS = [
    "ts_code",
    "trade_date",
    "total_mv",
    "float_mv",
    "total_share",
    "float_share",
    "free_share",
    "turnover_rate",
    "turnover_rate_f",
    "pe",
    "pe_ttm",
    "pb",
]

ETF_BASIC_FIELDS = [
    "ts_code",
    "csname",
    "extname",
    "cname",
    "index_code",
    "index_name",
    "setup_date",
    "list_date",
    "list_status",
    "exchange",
    "mgr_name",
    "custod_name",
    "mgt_fee",
    "etf_type",
]

ETF_INDEX_FIELDS = [
    "ts_code",
    "indx_name",
    "indx_csname",
    "pub_party_name",
    "pub_date",
    "base_date",
    "bp",
    "adj_circle",
]

FUND_ADJ_FIELDS = [
    "ts_code",
    "trade_date",
    "adj_factor",
]

BROKER_RECOMMEND_FIELDS = [
    "month",
    "currency",
    "name",
    "ts_code",
    "trade_date",
    "close",
    "pct_change",
    "target_price",
    "industry",
    "broker",
    "broker_mkt",
    "author",
    "recom_type",
    "reason",
]

HK_BASIC_FIELDS = [
    "ts_code",
    "name",
    "fullname",
    "enname",
    "cn_spell",
    "market",
    "list_status",
    "list_date",
    "delist_date",
    "trade_unit",
    "isin",
    "curr_type",
]

US_BASIC_FIELDS = [
    "ts_code",
    "name",
    "enname",
    "classify",
    "list_date",
    "delist_date",
]

THS_INDEX_FIELDS = ["ts_code", "name", "count", "exchange", "list_date", "type"]
THS_MEMBER_FIELDS = ["ts_code", "con_code", "con_name", "weight", "in_date", "out_date", "is_new"]
THS_DAILY_FIELDS = [
    "ts_code",
    "trade_date",
    "close",
    "open",
    "high",
    "low",
    "pre_close",
    "avg_price",
    "change",
    "pct_change",
    "vol",
    "turnover_rate",
    "total_mv",
    "float_mv",
]
DC_INDEX_FIELDS = [
    "ts_code",
    "trade_date",
    "name",
    "leading",
    "leading_code",
    "pct_change",
    "leading_pct",
    "total_mv",
    "turnover_rate",
    "up_num",
    "down_num",
    "idx_type",
    "level",
]
DC_MEMBER_FIELDS = ["trade_date", "ts_code", "con_code", "name"]
DC_DAILY_FIELDS = [
    "ts_code",
    "trade_date",
    "close",
    "open",
    "high",
    "low",
    "change",
    "pct_change",
    "vol",
    "amount",
    "swing",
    "turnover_rate",
]

THS_HOT_FIELDS = [
    "trade_date",
    "data_type",
    "ts_code",
    "ts_name",
    "rank",
    "pct_change",
    "current_price",
    "concept",
    "rank_reason",
    "hot",
    "rank_time",
]

DC_HOT_FIELDS = [
    "trade_date",
    "data_type",
    "ts_code",
    "ts_name",
    "rank",
    "pct_change",
    "current_price",
    "rank_time",
]

KPL_LIST_FIELDS = [
    "ts_code",
    "name",
    "trade_date",
    "lu_time",
    "ld_time",
    "open_time",
    "last_time",
    "lu_desc",
    "tag",
    "theme",
    "net_change",
    "bid_amount",
    "status",
    "bid_change",
    "bid_turnover",
    "lu_bid_vol",
    "pct_chg",
    "bid_pct_chg",
    "rt_pct_chg",
    "limit_order",
    "amount",
    "turnover_rate",
    "free_float",
    "lu_limit_order",
]

KPL_CONCEPT_CONS_FIELDS = [
    "ts_code",
    "name",
    "con_name",
    "con_code",
    "trade_date",
    "desc",
    "hot_num",
    "ts_name",
]
