"""Ports for local projection preparation, independent of Biz and Ops."""
from typing import Protocol
from contextlib import AbstractContextManager


class CatalogPreparationPort(Protocol):
    def check(self) -> None: ...
    def current(self, start: str, end: str) -> bool: ...
    def assert_source(self,full:bool=False) -> None: ...
    def prepare(self, query_id: str, conditions: dict) -> None: ...
    def preparation(self,query_id:str,conditions:dict) -> AbstractContextManager: ...
    def close(self) -> None: ...


class ArchivePresencePort(Protocol):
    identity: str
    def assert_valid(self,full:bool=False) -> None: ...
    def check(self, keys: list[str]) -> set[str]: ...
    def current_run(self) -> str | None: ...
    def close(self) -> None: ...
