"""Exact codes from wealth/docs/system/exception-code-registry.md §11."""

from typing import Literal

ErrorCode = Literal[
    "TA_REQUEST_INVALID", "TA_REQUEST_ID_CONFLICT", "TA_SCOPE_WRITE_PENDING", "TA_RECOVERY_UNAVAILABLE",
    "TA_RECOVERY_STATE_CHANGED", "TA_RECOVERY_QUERY_FAILED", "TA_WRITE_OUTCOME_UNKNOWN", "TA_WRITE_FAILED",
    "TA_ACCOUNT_NOT_FOUND", "TA_FEE_VERSION_CONFLICT", "TA_OBJECT_NOT_FOUND", "TA_STATE_CONFLICT",
    "TA_READ_CONTEXT_CHANGED", "TA_QUERY_FAILED",
]
