from lake_console.backend.app.sync.strategies.daily import DailyStrategy
from lake_console.backend.app.sync.strategies.index_basic import IndexBasicStrategy
from lake_console.backend.app.sync.strategies.prod_db_trade_date import (
    AdjFactorStrategy,
    CyqPerfStrategy,
    DailyBasicStrategy,
    DcDailyStrategy,
    DcHotStrategy,
    DcIndexStrategy,
    DcMemberStrategy,
    FundAdjStrategy,
    FundDailyStrategy,
    IndexDailyBasicStrategy,
    IndexDailyStrategy,
    KplConceptConsStrategy,
    KplListStrategy,
    LimitCptListStrategy,
    LimitListDStrategy,
    LimitListThsStrategy,
    LimitStepStrategy,
    MarginStrategy,
    MoneyflowCntThsStrategy,
    MoneyflowDcStrategy,
    MoneyflowIndDcStrategy,
    MoneyflowIndThsStrategy,
    MoneyflowMktDcStrategy,
    MoneyflowStrategy,
    MoneyflowThsStrategy,
    StkLimitStrategy,
    StockStStrategy,
    SuspendDStrategy,
    ThsDailyStrategy,
    ThsHotStrategy,
    TopListStrategy,
)
from lake_console.backend.app.sync.strategies.prod_raw_current_snapshots import (
    ETFBasicStrategy,
    ETFIndexStrategy,
    THSIndexStrategy,
    THSMemberStrategy,
)

STRATEGY_CLASSES = {
    AdjFactorStrategy.dataset_key: AdjFactorStrategy,
    CyqPerfStrategy.dataset_key: CyqPerfStrategy,
    DailyBasicStrategy.dataset_key: DailyBasicStrategy,
    DcDailyStrategy.dataset_key: DcDailyStrategy,
    DcHotStrategy.dataset_key: DcHotStrategy,
    DcIndexStrategy.dataset_key: DcIndexStrategy,
    DcMemberStrategy.dataset_key: DcMemberStrategy,
    DailyStrategy.dataset_key: DailyStrategy,
    ETFBasicStrategy.dataset_key: ETFBasicStrategy,
    ETFIndexStrategy.dataset_key: ETFIndexStrategy,
    FundAdjStrategy.dataset_key: FundAdjStrategy,
    FundDailyStrategy.dataset_key: FundDailyStrategy,
    IndexBasicStrategy.dataset_key: IndexBasicStrategy,
    IndexDailyBasicStrategy.dataset_key: IndexDailyBasicStrategy,
    IndexDailyStrategy.dataset_key: IndexDailyStrategy,
    KplConceptConsStrategy.dataset_key: KplConceptConsStrategy,
    KplListStrategy.dataset_key: KplListStrategy,
    LimitCptListStrategy.dataset_key: LimitCptListStrategy,
    LimitListDStrategy.dataset_key: LimitListDStrategy,
    LimitListThsStrategy.dataset_key: LimitListThsStrategy,
    LimitStepStrategy.dataset_key: LimitStepStrategy,
    MarginStrategy.dataset_key: MarginStrategy,
    MoneyflowStrategy.dataset_key: MoneyflowStrategy,
    MoneyflowThsStrategy.dataset_key: MoneyflowThsStrategy,
    MoneyflowDcStrategy.dataset_key: MoneyflowDcStrategy,
    MoneyflowCntThsStrategy.dataset_key: MoneyflowCntThsStrategy,
    MoneyflowIndThsStrategy.dataset_key: MoneyflowIndThsStrategy,
    MoneyflowIndDcStrategy.dataset_key: MoneyflowIndDcStrategy,
    MoneyflowMktDcStrategy.dataset_key: MoneyflowMktDcStrategy,
    StkLimitStrategy.dataset_key: StkLimitStrategy,
    StockStStrategy.dataset_key: StockStStrategy,
    SuspendDStrategy.dataset_key: SuspendDStrategy,
    ThsDailyStrategy.dataset_key: ThsDailyStrategy,
    ThsHotStrategy.dataset_key: ThsHotStrategy,
    TopListStrategy.dataset_key: TopListStrategy,
    THSIndexStrategy.dataset_key: THSIndexStrategy,
    THSMemberStrategy.dataset_key: THSMemberStrategy,
}

__all__ = [
    "STRATEGY_CLASSES",
    "AdjFactorStrategy",
    "CyqPerfStrategy",
    "DailyBasicStrategy",
    "DcDailyStrategy",
    "DcHotStrategy",
    "DcIndexStrategy",
    "DcMemberStrategy",
    "DailyStrategy",
    "ETFBasicStrategy",
    "ETFIndexStrategy",
    "FundAdjStrategy",
    "FundDailyStrategy",
    "IndexBasicStrategy",
    "IndexDailyBasicStrategy",
    "IndexDailyStrategy",
    "KplConceptConsStrategy",
    "KplListStrategy",
    "LimitCptListStrategy",
    "LimitListDStrategy",
    "LimitListThsStrategy",
    "LimitStepStrategy",
    "MarginStrategy",
    "MoneyflowStrategy",
    "MoneyflowThsStrategy",
    "MoneyflowDcStrategy",
    "MoneyflowCntThsStrategy",
    "MoneyflowIndThsStrategy",
    "MoneyflowIndDcStrategy",
    "MoneyflowMktDcStrategy",
    "StkLimitStrategy",
    "StockStStrategy",
    "SuspendDStrategy",
    "ThsDailyStrategy",
    "ThsHotStrategy",
    "TopListStrategy",
    "THSIndexStrategy",
    "THSMemberStrategy",
]
