from src.foundation.services.sync.registry import SYNC_SERVICE_REGISTRY


def test_registry_contains_required_resources() -> None:
    assert "stock_basic" in SYNC_SERVICE_REGISTRY
    assert "hk_basic" in SYNC_SERVICE_REGISTRY
    assert "us_basic" in SYNC_SERVICE_REGISTRY
    assert "etf_basic" in SYNC_SERVICE_REGISTRY
    assert "etf_index" in SYNC_SERVICE_REGISTRY
    assert "daily" in SYNC_SERVICE_REGISTRY
    assert "equity_indicators" in SYNC_SERVICE_REGISTRY
    assert "fund_daily" in SYNC_SERVICE_REGISTRY
    assert "fund_adj" in SYNC_SERVICE_REGISTRY
    assert "margin" in SYNC_SERVICE_REGISTRY
    assert "broker_recommend" in SYNC_SERVICE_REGISTRY
    assert "stk_period_bar_week" in SYNC_SERVICE_REGISTRY
    assert "index_weight" in SYNC_SERVICE_REGISTRY
    assert "ths_daily" in SYNC_SERVICE_REGISTRY
    assert "dc_index" in SYNC_SERVICE_REGISTRY
    assert "dc_member" in SYNC_SERVICE_REGISTRY
    assert "dc_daily" in SYNC_SERVICE_REGISTRY
    assert "ths_hot" in SYNC_SERVICE_REGISTRY
    assert "dc_hot" in SYNC_SERVICE_REGISTRY
    assert "kpl_list" in SYNC_SERVICE_REGISTRY
    assert "kpl_concept_cons" in SYNC_SERVICE_REGISTRY
    assert "biying_moneyflow" in SYNC_SERVICE_REGISTRY
    assert "stk_limit" in SYNC_SERVICE_REGISTRY
    assert "stk_nineturn" in SYNC_SERVICE_REGISTRY
    assert "suspend_d" in SYNC_SERVICE_REGISTRY
