"""rebuild stk_factor_pro tables with source output fields

Revision ID: 20260423_000070
Revises: 20260421_000069
Create Date: 2026-04-23
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "20260423_000070"
down_revision = "20260421_000069"
branch_labels = None
depends_on = None


STK_FACTOR_PRO_VALUE_COLUMNS: tuple[str, ...] = (
    "open",
    "open_hfq",
    "open_qfq",
    "high",
    "high_hfq",
    "high_qfq",
    "low",
    "low_hfq",
    "low_qfq",
    "close",
    "close_hfq",
    "close_qfq",
    "pre_close",
    "change",
    "pct_chg",
    "vol",
    "amount",
    "turnover_rate",
    "turnover_rate_f",
    "volume_ratio",
    "pe",
    "pe_ttm",
    "pb",
    "ps",
    "ps_ttm",
    "dv_ratio",
    "dv_ttm",
    "total_share",
    "float_share",
    "free_share",
    "total_mv",
    "circ_mv",
    "adj_factor",
    "asi_bfq",
    "asi_hfq",
    "asi_qfq",
    "asit_bfq",
    "asit_hfq",
    "asit_qfq",
    "atr_bfq",
    "atr_hfq",
    "atr_qfq",
    "bbi_bfq",
    "bbi_hfq",
    "bbi_qfq",
    "bias1_bfq",
    "bias1_hfq",
    "bias1_qfq",
    "bias2_bfq",
    "bias2_hfq",
    "bias2_qfq",
    "bias3_bfq",
    "bias3_hfq",
    "bias3_qfq",
    "boll_lower_bfq",
    "boll_lower_hfq",
    "boll_lower_qfq",
    "boll_mid_bfq",
    "boll_mid_hfq",
    "boll_mid_qfq",
    "boll_upper_bfq",
    "boll_upper_hfq",
    "boll_upper_qfq",
    "brar_ar_bfq",
    "brar_ar_hfq",
    "brar_ar_qfq",
    "brar_br_bfq",
    "brar_br_hfq",
    "brar_br_qfq",
    "cci_bfq",
    "cci_hfq",
    "cci_qfq",
    "cr_bfq",
    "cr_hfq",
    "cr_qfq",
    "dfma_dif_bfq",
    "dfma_dif_hfq",
    "dfma_dif_qfq",
    "dfma_difma_bfq",
    "dfma_difma_hfq",
    "dfma_difma_qfq",
    "dmi_adx_bfq",
    "dmi_adx_hfq",
    "dmi_adx_qfq",
    "dmi_adxr_bfq",
    "dmi_adxr_hfq",
    "dmi_adxr_qfq",
    "dmi_mdi_bfq",
    "dmi_mdi_hfq",
    "dmi_mdi_qfq",
    "dmi_pdi_bfq",
    "dmi_pdi_hfq",
    "dmi_pdi_qfq",
    "downdays",
    "updays",
    "dpo_bfq",
    "dpo_hfq",
    "dpo_qfq",
    "madpo_bfq",
    "madpo_hfq",
    "madpo_qfq",
    "ema_bfq_10",
    "ema_bfq_20",
    "ema_bfq_250",
    "ema_bfq_30",
    "ema_bfq_5",
    "ema_bfq_60",
    "ema_bfq_90",
    "ema_hfq_10",
    "ema_hfq_20",
    "ema_hfq_250",
    "ema_hfq_30",
    "ema_hfq_5",
    "ema_hfq_60",
    "ema_hfq_90",
    "ema_qfq_10",
    "ema_qfq_20",
    "ema_qfq_250",
    "ema_qfq_30",
    "ema_qfq_5",
    "ema_qfq_60",
    "ema_qfq_90",
    "emv_bfq",
    "emv_hfq",
    "emv_qfq",
    "maemv_bfq",
    "maemv_hfq",
    "maemv_qfq",
    "expma_12_bfq",
    "expma_12_hfq",
    "expma_12_qfq",
    "expma_50_bfq",
    "expma_50_hfq",
    "expma_50_qfq",
    "kdj_bfq",
    "kdj_hfq",
    "kdj_qfq",
    "kdj_d_bfq",
    "kdj_d_hfq",
    "kdj_d_qfq",
    "kdj_k_bfq",
    "kdj_k_hfq",
    "kdj_k_qfq",
    "ktn_down_bfq",
    "ktn_down_hfq",
    "ktn_down_qfq",
    "ktn_mid_bfq",
    "ktn_mid_hfq",
    "ktn_mid_qfq",
    "ktn_upper_bfq",
    "ktn_upper_hfq",
    "ktn_upper_qfq",
    "lowdays",
    "topdays",
    "ma_bfq_10",
    "ma_bfq_20",
    "ma_bfq_250",
    "ma_bfq_30",
    "ma_bfq_5",
    "ma_bfq_60",
    "ma_bfq_90",
    "ma_hfq_10",
    "ma_hfq_20",
    "ma_hfq_250",
    "ma_hfq_30",
    "ma_hfq_5",
    "ma_hfq_60",
    "ma_hfq_90",
    "ma_qfq_10",
    "ma_qfq_20",
    "ma_qfq_250",
    "ma_qfq_30",
    "ma_qfq_5",
    "ma_qfq_60",
    "ma_qfq_90",
    "macd_bfq",
    "macd_hfq",
    "macd_qfq",
    "macd_dea_bfq",
    "macd_dea_hfq",
    "macd_dea_qfq",
    "macd_dif_bfq",
    "macd_dif_hfq",
    "macd_dif_qfq",
    "mass_bfq",
    "mass_hfq",
    "mass_qfq",
    "ma_mass_bfq",
    "ma_mass_hfq",
    "ma_mass_qfq",
    "mfi_bfq",
    "mfi_hfq",
    "mfi_qfq",
    "mtm_bfq",
    "mtm_hfq",
    "mtm_qfq",
    "mtmma_bfq",
    "mtmma_hfq",
    "mtmma_qfq",
    "obv_bfq",
    "obv_hfq",
    "obv_qfq",
    "psy_bfq",
    "psy_hfq",
    "psy_qfq",
    "psyma_bfq",
    "psyma_hfq",
    "psyma_qfq",
    "roc_bfq",
    "roc_hfq",
    "roc_qfq",
    "maroc_bfq",
    "maroc_hfq",
    "maroc_qfq",
    "rsi_bfq_12",
    "rsi_bfq_24",
    "rsi_bfq_6",
    "rsi_hfq_12",
    "rsi_hfq_24",
    "rsi_hfq_6",
    "rsi_qfq_12",
    "rsi_qfq_24",
    "rsi_qfq_6",
    "taq_down_bfq",
    "taq_down_hfq",
    "taq_down_qfq",
    "taq_mid_bfq",
    "taq_mid_hfq",
    "taq_mid_qfq",
    "taq_up_bfq",
    "taq_up_hfq",
    "taq_up_qfq",
    "trix_bfq",
    "trix_hfq",
    "trix_qfq",
    "trma_bfq",
    "trma_hfq",
    "trma_qfq",
    "vr_bfq",
    "vr_hfq",
    "vr_qfq",
    "wr_bfq",
    "wr_hfq",
    "wr_qfq",
    "wr1_bfq",
    "wr1_hfq",
    "wr1_qfq",
    "xsii_td1_bfq",
    "xsii_td1_hfq",
    "xsii_td1_qfq",
    "xsii_td2_bfq",
    "xsii_td2_hfq",
    "xsii_td2_qfq",
    "xsii_td3_bfq",
    "xsii_td3_hfq",
    "xsii_td3_qfq",
    "xsii_td4_bfq",
    "xsii_td4_hfq",
    "xsii_td4_qfq",
)


def _create_raw_table() -> None:
    op.create_table(
        "stk_factor_pro",
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        *[sa.Column(column_name, sa.Float(53)) for column_name in STK_FACTOR_PRO_VALUE_COLUMNS],
        sa.Column("api_name", sa.String(length=32), nullable=False, server_default=sa.text("'stk_factor_pro'")),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("raw_payload", sa.Text()),
        sa.PrimaryKeyConstraint("ts_code", "trade_date"),
        schema="raw_tushare",
    )
    op.create_index(
        "idx_raw_tushare_stk_factor_pro_trade_date",
        "stk_factor_pro",
        ["trade_date"],
        schema="raw_tushare",
    )
    op.create_index(
        "idx_raw_tushare_stk_factor_pro_ts_code_trade_date",
        "stk_factor_pro",
        ["ts_code", "trade_date"],
        schema="raw_tushare",
    )


def _create_serving_table() -> None:
    op.create_table(
        "equity_factor_pro",
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        *[sa.Column(column_name, sa.Float(53)) for column_name in STK_FACTOR_PRO_VALUE_COLUMNS],
        sa.Column("source", sa.String(length=32), nullable=False, server_default=sa.text("'tushare'")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("ts_code", "trade_date"),
        schema="core_serving",
    )
    op.create_index(
        "idx_equity_factor_pro_trade_date",
        "equity_factor_pro",
        ["trade_date"],
        schema="core_serving",
    )
    op.create_index(
        "idx_equity_factor_pro_ts_code_trade_date",
        "equity_factor_pro",
        ["ts_code", "trade_date"],
        schema="core_serving",
    )


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS raw_tushare")
    op.execute("CREATE SCHEMA IF NOT EXISTS core_serving")

    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table("stk_factor_pro", schema="raw_tushare"):
        op.drop_table("stk_factor_pro", schema="raw_tushare")
    if inspector.has_table("equity_factor_pro", schema="core_serving"):
        op.drop_table("equity_factor_pro", schema="core_serving")

    _create_raw_table()
    _create_serving_table()


def downgrade() -> None:
    # 本次为明确的 drop+recreate 重建迁移，降级不做旧结构恢复。
    pass

