"""Frozen robot credential/configuration evidence; no network or data deletion."""
from alembic import op

revision = "20260916_000178"
down_revision = "20260915_000177"
branch_labels = None
depends_on = None

DDL = (
    "CREATE TABLE app.wealth_ta_credential_blob (\n\tblob_id UUID NOT NULL, \n\towner_user_id INTEGER NOT NULL, \n\tobject_type TEXT NOT NULL, \n\tobject_id UUID NOT NULL, \n\tkey_id TEXT NOT NULL, \n\tnonce BYTEA NOT NULL, \n\tciphertext BYTEA NOT NULL, \n\talgorithm_version TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_wealth_ta_credential_blob PRIMARY KEY (blob_id), \n\tCONSTRAINT uq_ta_credential_nonce UNIQUE (key_id, nonce), \n\tCONSTRAINT uq_ta_credential_object UNIQUE (owner_user_id, object_type, object_id), \n\tCONSTRAINT uq_ta_credential_reference UNIQUE (owner_user_id, object_type, object_id, blob_id), \n\tCONSTRAINT ck_wealth_ta_credential_blob_object_type CHECK (object_type IN ('CANDIDATE','CONFIG')), \n\tCONSTRAINT ck_wealth_ta_credential_blob_envelope CHECK (algorithm_version = 'AES256_GCM_V1' AND length(key_id) > 0 AND octet_length(nonce) = 12 AND octet_length(ciphertext) >= 16), \n\tCONSTRAINT fk_wealth_ta_credential_blob_owner_user_id_app_user FOREIGN KEY(owner_user_id) REFERENCES app.app_user (id) ON DELETE RESTRICT\n)",
    "CREATE TABLE app.wealth_ta_robot_candidate (\n\tcandidate_id UUID NOT NULL, \n\towner_user_id INTEGER NOT NULL, \n\trobot_id UUID NOT NULL, \n\tcandidate_version BIGINT NOT NULL, \n\texpected_config_id UUID, \n\tname TEXT NOT NULL, \n\tkeywords TEXT[] NOT NULL, \n\tcontent_digest TEXT NOT NULL, \n\tcredential_blob_id UUID NOT NULL, \n\tcredential_object_type TEXT DEFAULT 'CANDIDATE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_wealth_ta_robot_candidate PRIMARY KEY (candidate_id), \n\tCONSTRAINT fk_wealth_ta_robot_candidate_owner_user_id_wealth_ta_robot FOREIGN KEY(owner_user_id, robot_id) REFERENCES app.wealth_ta_robot (owner_user_id, robot_id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_wealth_ta_robot_candidate_owner_user_id_wealth_ta_cr_63d7 FOREIGN KEY(owner_user_id, credential_object_type, candidate_id, credential_blob_id) REFERENCES app.wealth_ta_credential_blob (owner_user_id, object_type, object_id, blob_id) ON DELETE RESTRICT, \n\tCONSTRAINT uq_ta_robot_candidate_identity UNIQUE (owner_user_id, robot_id, candidate_id), \n\tCONSTRAINT ck_wealth_ta_robot_candidate_identity CHECK (credential_object_type = 'CANDIDATE' AND candidate_version >= 1), \n\tCONSTRAINT ck_wealth_ta_robot_candidate_content CHECK (length(btrim(name)) > 0 AND content_digest ~ '^[0-9a-f]{64}$'), \n\tCONSTRAINT ck_wealth_ta_robot_candidate_keywords CHECK (cardinality(keywords) <= 10 AND array_position(keywords, NULL) IS NULL)\n)",
    "CREATE TABLE app.wealth_ta_robot_test (\n\ttest_id UUID NOT NULL, \n\towner_user_id INTEGER NOT NULL, \n\trobot_id UUID NOT NULL, \n\tcandidate_id UUID NOT NULL, \n\tattempt_no BIGINT NOT NULL, \n\tstate TEXT NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\treason TEXT, \n\tCONSTRAINT pk_wealth_ta_robot_test PRIMARY KEY (test_id), \n\tCONSTRAINT fk_wealth_ta_robot_test_owner_user_id_wealth_ta_robot_candidate FOREIGN KEY(owner_user_id, robot_id, candidate_id) REFERENCES app.wealth_ta_robot_candidate (owner_user_id, robot_id, candidate_id) ON DELETE RESTRICT, \n\tCONSTRAINT uq_ta_robot_test_attempt UNIQUE (candidate_id, attempt_no), \n\tCONSTRAINT uq_ta_robot_test_evidence UNIQUE (owner_user_id, robot_id, candidate_id, test_id, state), \n\tCONSTRAINT ck_wealth_ta_robot_test_attempt CHECK (attempt_no >= 1), \n\tCONSTRAINT ck_wealth_ta_robot_test_state CHECK ((state = 'IN_FLIGHT' AND completed_at IS NULL AND reason IS NULL) OR (state IN ('SUCCEEDED','FAILED','UNKNOWN') AND completed_at IS NOT NULL AND completed_at >= started_at))\n)",
    "CREATE UNIQUE INDEX uq_ta_robot_test_inflight ON app.wealth_ta_robot_test (candidate_id) WHERE state = 'IN_FLIGHT'",
    "CREATE TABLE app.wealth_ta_robot_config (\n\tconfig_id UUID NOT NULL, \n\towner_user_id INTEGER NOT NULL, \n\trobot_id UUID NOT NULL, \n\tcandidate_id UUID NOT NULL, \n\ttest_id UUID NOT NULL, \n\ttest_state TEXT DEFAULT 'SUCCEEDED' NOT NULL, \n\tname TEXT NOT NULL, \n\tkeywords TEXT[] NOT NULL, \n\tcredential_blob_id UUID NOT NULL, \n\tcredential_object_type TEXT DEFAULT 'CONFIG' NOT NULL, \n\tconfirmed_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_wealth_ta_robot_config PRIMARY KEY (config_id), \n\tCONSTRAINT fk_wealth_ta_robot_config_owner_user_id_wealth_ta_robot FOREIGN KEY(owner_user_id, robot_id) REFERENCES app.wealth_ta_robot (owner_user_id, robot_id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_wealth_ta_robot_config_owner_user_id_wealth_ta_crede_225f FOREIGN KEY(owner_user_id, credential_object_type, config_id, credential_blob_id) REFERENCES app.wealth_ta_credential_blob (owner_user_id, object_type, object_id, blob_id) ON DELETE RESTRICT, \n\tCONSTRAINT uq_ta_robot_config_identity UNIQUE (owner_user_id, robot_id, config_id), \n\tCONSTRAINT uq_ta_robot_config_candidate UNIQUE (candidate_id), \n\tCONSTRAINT fk_wealth_ta_robot_config_owner_user_id_wealth_ta_robot_test FOREIGN KEY(owner_user_id, robot_id, candidate_id, test_id, test_state) REFERENCES app.wealth_ta_robot_test (owner_user_id, robot_id, candidate_id, test_id, state) ON DELETE RESTRICT, \n\tCONSTRAINT ck_wealth_ta_robot_config_evidence CHECK (credential_object_type = 'CONFIG' AND test_state = 'SUCCEEDED'), \n\tCONSTRAINT ck_wealth_ta_robot_config_name CHECK (length(btrim(name)) > 0), \n\tCONSTRAINT ck_wealth_ta_robot_config_keywords CHECK (cardinality(keywords) <= 10 AND array_position(keywords, NULL) IS NULL)\n)",
    "ALTER TABLE app.wealth_ta_robot_candidate ADD CONSTRAINT fk_ta_candidate_expected_config FOREIGN KEY(owner_user_id, robot_id, expected_config_id) REFERENCES app.wealth_ta_robot_config (owner_user_id, robot_id, config_id) ON DELETE RESTRICT",
    "ALTER TABLE app.wealth_ta_robot ADD CONSTRAINT fk_ta_robot_current_config FOREIGN KEY (owner_user_id, robot_id, current_config_id) REFERENCES app.wealth_ta_robot_config (owner_user_id, robot_id, config_id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED",
)


def upgrade():
    for statement in DDL:
        op.execute(statement)


def downgrade():
    raise RuntimeError("Robot configuration evidence must not be dropped automatically")
