-- Explicit local archive schema v1. Only the migration tool executes this file.

CREATE SCHEMA announcement_archive;

CREATE TABLE announcement_archive.schema_info (
    singleton SMALLINT NOT NULL,
    version BIGINT NOT NULL,
    ddl_sha256 TEXT NOT NULL,
    installed_at TEXT NOT NULL,
    PRIMARY KEY (singleton),
    CHECK (singleton=1)
);

CREATE TABLE announcement_archive.archives (
    archive_id TEXT NOT NULL,
    volume_uuid TEXT NOT NULL,
    root_relative_path TEXT NOT NULL,
    created_at TEXT NOT NULL,
    source_schema_version BIGINT NOT NULL,
    import_state TEXT NOT NULL,
    import_completed_at TEXT,
    PRIMARY KEY (archive_id),
    UNIQUE (volume_uuid,root_relative_path),
    CHECK (import_state IN ('importing','ready'))
);

CREATE TABLE announcement_archive.runs (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_id TEXT NOT NULL,
    start_date TEXT,
    end_date TEXT,
    interval_seconds DOUBLE PRECISION,
    source_scope TEXT,
    legacy_upper_id BIGINT DEFAULT 0,
    legacy_after_id BIGINT DEFAULT 0,
    phase TEXT NOT NULL,
    records_read BIGINT DEFAULT 0,
    reason TEXT,
    updated_at TEXT,
    missing_url_count BIGINT DEFAULT 0,
    artifacts_total BIGINT DEFAULT 0,
    completed_count BIGINT DEFAULT 0,
    succeeded_count BIGINT DEFAULT 0,
    skipped_count BIGINT DEFAULT 0,
    failed_count BIGINT DEFAULT 0,
    source_kind TEXT NOT NULL DEFAULT 'dg_raw_parquet',
    source_contract_version BIGINT,
    source_policy TEXT,
    days_total BIGINT,
    days_completed BIGINT NOT NULL DEFAULT 0,
    current_day TEXT,
    enumeration_sealed BIGINT NOT NULL DEFAULT 0,
    batch_kind TEXT NOT NULL DEFAULT 'date',
    parent_run_id TEXT,
    retry_of_run_id TEXT,
    preview_id TEXT,
    created_at TEXT,
    started_at TEXT,
    finished_at TEXT,
    actor_id TEXT,
    owner_token TEXT,
    heartbeat_at TEXT,
    business_updated_at TEXT,
    stop_requested_at TEXT,
    resume_count BIGINT NOT NULL DEFAULT 0,
    current_artifact_key TEXT,
    attempt_number BIGINT NOT NULL DEFAULT 0,
    bytes_received BIGINT NOT NULL DEFAULT 0,
    bytes_total BIGINT,
    wait_kind TEXT,
    next_request_at DOUBLE PRECISION,
    revision BIGINT NOT NULL DEFAULT 0,
    check_state TEXT,
    check_kind TEXT,
    check_code TEXT,
    check_updated_at TEXT,
    PRIMARY KEY (archive_id,run_id),
    UNIQUE (archive_id,row_seq)
);

CREATE TABLE announcement_archive.artifacts (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    artifact_key TEXT NOT NULL,
    ann_date TEXT,
    ts_code TEXT,
    title TEXT,
    url TEXT,
    relative_path TEXT,
    path_fold TEXT,
    state TEXT NOT NULL DEFAULT 'pending',
    error TEXT,
    attempts BIGINT NOT NULL DEFAULT 0,
    size BIGINT,
    sha256 TEXT,
    updated_at TEXT,
    created_run_id TEXT,
    representative_record_key TEXT,
    PRIMARY KEY (archive_id,artifact_key),
    UNIQUE (archive_id,path_fold)
);

CREATE TABLE announcement_archive.source_records (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_scope TEXT NOT NULL,
    record_key TEXT NOT NULL,
    legacy_raw_id BIGINT,
    metadata TEXT,
    artifact_key TEXT,
    first_seen_run TEXT,
    last_seen_run TEXT,
    PRIMARY KEY (archive_id,source_scope,record_key),
    UNIQUE (archive_id,row_seq)
);

CREATE TABLE announcement_archive.run_artifacts (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    run_id TEXT NOT NULL,
    artifact_key TEXT NOT NULL,
    outcome TEXT,
    attempts BIGINT DEFAULT 0,
    representative_record_key TEXT,
    claimed_owner TEXT,
    claimed_at TEXT,
    PRIMARY KEY (archive_id,run_id,artifact_key)
);

CREATE TABLE announcement_archive.run_source_days (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    run_id TEXT NOT NULL,
    ann_date TEXT NOT NULL,
    state TEXT NOT NULL,
    opened_dev BIGINT,
    opened_ino BIGINT,
    size BIGINT,
    sha256 TEXT,
    footer_count BIGINT,
    records_committed BIGINT NOT NULL DEFAULT 0,
    reason TEXT,
    updated_at TEXT,
    PRIMARY KEY (archive_id,run_id,ann_date)
);

CREATE TABLE announcement_archive.cooldown (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    last_request_finished_at DOUBLE PRECISION DEFAULT 0,
    next_request_not_before DOUBLE PRECISION DEFAULT 0,
    request_in_flight BIGINT DEFAULT 0,
    reason TEXT,
    PRIMARY KEY (archive_id)
);

CREATE TABLE announcement_archive.archive_execution (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    active_run_id TEXT,
    owner_token TEXT,
    heartbeat TEXT,
    revision BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (archive_id)
);

CREATE TABLE announcement_archive.attempt_log (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    run_id TEXT NOT NULL,
    artifact_key TEXT NOT NULL,
    attempt_seq BIGINT NOT NULL,
    session_seq BIGINT NOT NULL,
    started_at TEXT NOT NULL,
    ended_at TEXT,
    outcome TEXT,
    reason TEXT,
    http_status BIGINT,
    bytes BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (archive_id,run_id,artifact_key,attempt_seq)
);

CREATE TABLE announcement_archive.run_sessions (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    run_id TEXT NOT NULL,
    session_seq BIGINT NOT NULL,
    started_at TEXT NOT NULL,
    ended_at TEXT,
    owner_token TEXT NOT NULL,
    reason TEXT,
    PRIMARY KEY (archive_id,run_id,session_seq)
);

CREATE TABLE announcement_archive.command_receipts (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    key TEXT NOT NULL,
    kind TEXT NOT NULL,
    payload_hash TEXT NOT NULL,
    result_run_id TEXT,
    state TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (archive_id,key)
);

CREATE TABLE announcement_archive.query_snapshots (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    query_id TEXT NOT NULL,
    source_scope TEXT NOT NULL,
    conditions TEXT NOT NULL,
    state TEXT NOT NULL,
    source_version TEXT,
    total BIGINT,
    status_available BIGINT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    checked_at TEXT,
    expires_at DOUBLE PRECISION,
    reason TEXT,
    preparation_stage TEXT NOT NULL,
    dates_total BIGINT NOT NULL DEFAULT 0,
    dates_scanned BIGINT NOT NULL DEFAULT 0,
    records_scanned BIGINT NOT NULL DEFAULT 0,
    artifacts_checked BIGINT NOT NULL DEFAULT 0,
    owner_token TEXT,
    PRIMARY KEY (archive_id,query_id)
);

CREATE TABLE announcement_archive.query_files (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    query_id TEXT NOT NULL,
    source_kind TEXT NOT NULL,
    partition TEXT NOT NULL,
    relative_path TEXT NOT NULL,
    opened_dev BIGINT NOT NULL,
    opened_ino BIGINT NOT NULL,
    size BIGINT NOT NULL,
    mtime_ns BIGINT NOT NULL,
    footer_count BIGINT NOT NULL,
    PRIMARY KEY (archive_id,query_id,source_kind,partition)
);

CREATE TABLE announcement_archive.query_day_counts (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    query_id TEXT NOT NULL,
    ann_date TEXT NOT NULL,
    match_count BIGINT NOT NULL,
    PRIMARY KEY (archive_id,query_id,ann_date)
);

CREATE TABLE announcement_archive.query_presence (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    query_id TEXT NOT NULL,
    artifact_key TEXT NOT NULL,
    checked_at TEXT NOT NULL,
    PRIMARY KEY (archive_id,query_id,artifact_key)
);

CREATE TABLE announcement_archive.previews (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    preview_id TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    interval_seconds DOUBLE PRECISION NOT NULL,
    source_scope TEXT NOT NULL,
    source_version TEXT,
    state TEXT NOT NULL,
    statistics TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    expires_at DOUBLE PRECISION,
    reason TEXT,
    dates_total BIGINT NOT NULL DEFAULT 0,
    dates_scanned BIGINT NOT NULL DEFAULT 0,
    records_scanned BIGINT NOT NULL DEFAULT 0,
    owner_token TEXT,
    PRIMARY KEY (archive_id,preview_id)
);

CREATE TABLE announcement_archive.preview_days (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    preview_id TEXT NOT NULL,
    ann_date TEXT NOT NULL,
    source_facts TEXT NOT NULL,
    PRIMARY KEY (archive_id,preview_id,ann_date)
);

CREATE TABLE announcement_archive.preview_artifacts (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    preview_id TEXT NOT NULL,
    artifact_key TEXT NOT NULL,
    PRIMARY KEY (archive_id,preview_id,artifact_key)
);

CREATE TABLE announcement_archive.migration_checkpoints (
    archive_id TEXT NOT NULL REFERENCES announcement_archive.archives(archive_id),
    source_table TEXT NOT NULL,
    source_path TEXT NOT NULL,
    source_sha256 TEXT NOT NULL,
    source_schema_version BIGINT NOT NULL,
    last_rowid BIGINT NOT NULL,
    rows_committed BIGINT NOT NULL,
    rows_total BIGINT NOT NULL,
    rows_digest TEXT NOT NULL,
    state TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (archive_id,source_table)
);

CREATE INDEX runs_order ON announcement_archive.runs(archive_id,row_seq DESC);

CREATE INDEX artifact_date_code ON announcement_archive.artifacts(archive_id,ann_date,ts_code,artifact_key);

CREATE INDEX artifact_success ON announcement_archive.artifacts(archive_id,artifact_key) WHERE state='succeeded';

CREATE INDEX source_artifact_order ON announcement_archive.source_records(archive_id,artifact_key,row_seq);

CREATE INDEX run_pending ON announcement_archive.run_artifacts(archive_id,run_id,outcome,artifact_key);

CREATE INDEX source_day_state ON announcement_archive.run_source_days(archive_id,run_id,state,ann_date);

CREATE INDEX attempt_open ON announcement_archive.attempt_log(archive_id,run_id,artifact_key) WHERE ended_at IS NULL;

CREATE INDEX session_open ON announcement_archive.run_sessions(archive_id,run_id) WHERE ended_at IS NULL;

CREATE INDEX query_snapshots_pending ON announcement_archive.query_snapshots(archive_id,state,created_at);

CREATE INDEX query_snapshots_expiry ON announcement_archive.query_snapshots(expires_at);

CREATE INDEX previews_pending ON announcement_archive.previews(archive_id,state,created_at);

CREATE INDEX previews_expiry ON announcement_archive.previews(expires_at);
