import { act, renderHook, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useRecords } from "./useRecords";
import { defaultRecordFilter } from "./recordsQuery";
import { TradingAssistantApiError } from "../api/tradingAssistantApi";
const mock = vi.hoisted(() => ({ summary: vi.fn(), trades: vi.fn(), cash: vi.fn(), groups: vi.fn(), closed: vi.fn(), status: vi.fn() }));
vi.mock("../api/positionsApi", () => ({ getCalculationStatus: mock.status }));
vi.mock("../api/recordsApi", () => ({ getRecordsSummary: mock.summary, getTradeRecords: mock.trades, getCashRecords: mock.cash, getTradeDayGroups: mock.groups, getClosedRecords: mock.closed }));
const filter = defaultRecordFilter();
const totals = (id: string) => ({ scope: { accountMode: "SINGLE", accounts: [{ accountId: id }] }, requestedStartDate: filter.start, requestedEndDate: filter.end, closedTradeCount: 0, readContext: { contextToken: id, accounts: [] } });
const page = (id: string, nextCursor: string | null = null) => ({ items: [], nextCursor, readContext: { contextToken: id }, coverage: { accounts: [] } });
describe("records read coordination", () => {
  beforeEach(() => { vi.clearAllMocks(); mock.summary.mockImplementation(async q => totals(q.accountId)); mock.trades.mockImplementation(async q => page(q.accountId, q.cursor ? null : "next")); });
  afterEach(() => { vi.useRealTimers(); vi.restoreAllMocks(); });
  it("keeps the full-range summary across pagination and resets cursors on new filters", async () => {
    const hook = renderHook(({ f }) => useRecords("one", "TRADE", f, null, 0), { initialProps: { f: filter } });
    await waitFor(() => expect(hook.result.current.page).not.toBeNull());
    act(() => hook.result.current.next());
    await waitFor(() => expect(hook.result.current.page?.data.nextCursor).toBeNull());
    expect(mock.summary).toHaveBeenCalledTimes(1); expect(mock.trades.mock.calls[1][0].cursor).toBe("next");
    hook.rerender({ f: { ...filter, start: filter.end } });
    await waitFor(() => expect(hook.result.current.page).not.toBeNull());
    expect(hook.result.current.pageIndex).toBe(0); expect(mock.trades.mock.calls.at(-1)![0]).not.toHaveProperty("cursor");
    hook.unmount();
  });
  it("aborts old account reads and ignores responses from clients that ignore abort", async () => {
    let complete!: (value: unknown) => void;
    mock.summary.mockImplementationOnce(() => new Promise(resolve => { complete = resolve; }));
    const hook = renderHook(({ id }) => useRecords(id, "TRADE", filter, null, 0), { initialProps: { id: "one" } });
    const signal = mock.summary.mock.calls[0][1];
    hook.rerender({ id: "two" });
    expect(signal.aborted).toBe(true);
    await waitFor(() => expect(hook.result.current.summary?.readContext.contextToken).toBe("two"));
    await act(async () => complete(totals("one")));
    expect(hook.result.current.summary?.readContext.contextToken).toBe("two");
    hook.unmount();
  });
  it("recaptures the summary after a write while retaining the applied filter", async () => {
    const applied = { ...filter, start: filter.end, direction: "SELL" };
    const hook = renderHook(({ revision }) => useRecords("one", "TRADE", applied, null, revision), { initialProps: { revision: 0 } });
    await waitFor(() => expect(hook.result.current.page).not.toBeNull());
    hook.rerender({ revision: 1 });
    await waitFor(() => expect(mock.summary).toHaveBeenCalledTimes(2));
    await waitFor(() => expect(hook.result.current.page).not.toBeNull());
    expect(mock.trades.mock.calls.at(-1)![0]).toMatchObject({ requestedStartDate: applied.start, direction: "SELL" });
    hook.unmount();
  });
  it("drops an expired cursor and recaptures the entire group on a context change", async () => {
    const hook = renderHook(() => useRecords("one", "TRADE", filter, null, 0));
    await waitFor(() => expect(hook.result.current.page).not.toBeNull());
    mock.trades.mockRejectedValueOnce(new TradingAssistantApiError({ code: "TA_READ_CONTEXT_CHANGED", message: "changed", fieldErrors: [] } as never));
    act(() => hook.result.current.next());
    await waitFor(() => expect(mock.summary).toHaveBeenCalledTimes(2));
    await waitFor(() => expect(hook.result.current.page).not.toBeNull());
    expect(hook.result.current.pageIndex).toBe(0);
    expect(mock.trades.mock.calls.at(-1)![0]).not.toHaveProperty("cursor");
    expect(hook.result.current.error).toBe(false);
    hook.unmount();
  });
  it("checks waiting data at the approved cadence and stops polling a terminal generation", async () => {
    vi.useFakeTimers();
    vi.spyOn(document, "visibilityState", "get").mockReturnValue("visible");
    mock.summary.mockImplementation(async () => ({ ...totals("one"), closedTradeCount: null, readContext: { contextToken: "one", accounts: [{ accountId: "one", calculationTargetVersion: "1" }] } }));
    mock.trades.mockImplementation(async () => ({ ...page("one"), coverage: { accounts: [{ accountId: "one", dataStatus: "Delayed" }] } }));
    mock.status.mockResolvedValue({ stage: "WAITING_DATA", calculationTargetVersion: "1" });
    const hook = renderHook(() => useRecords("one", "TRADE", filter, null, 0));
    await act(async () => {});
    await act(async () => vi.advanceTimersByTimeAsync(2000));
    expect(mock.status).toHaveBeenCalledTimes(1);
    await act(async () => vi.advanceTimersByTimeAsync(59999));
    expect(mock.status).toHaveBeenCalledTimes(1);
    mock.status.mockResolvedValue({ stage: "FAILED", calculationTargetVersion: "1" });
    await act(async () => vi.advanceTimersByTimeAsync(1));
    expect(mock.status).toHaveBeenCalledTimes(2);
    expect(mock.summary).toHaveBeenCalledTimes(2);
    await act(async () => vi.advanceTimersByTimeAsync(60000));
    expect(mock.status).toHaveBeenCalledTimes(2);
    hook.unmount();
  });
  it("cancels an in-flight status request when hidden and recaptures on return", async () => {
    vi.useFakeTimers();
    const visibility = vi.spyOn(document, "visibilityState", "get").mockReturnValue("visible");
    mock.summary.mockImplementation(async () => ({ ...totals("one"), closedTradeCount: null }));
    mock.trades.mockImplementation(async () => ({ ...page("one"), coverage: { accounts: [{ accountId: "one", dataStatus: "Delayed" }] } }));
    mock.status.mockImplementation(() => new Promise(() => {}));
    const hook = renderHook(() => useRecords("one", "TRADE", filter, null, 0));
    await act(async () => {});
    await act(async () => vi.advanceTimersByTimeAsync(2000));
    const signal = mock.status.mock.calls[0][1];
    visibility.mockReturnValue("hidden");
    act(() => document.dispatchEvent(new Event("visibilitychange")));
    expect(signal.aborted).toBe(true);
    visibility.mockReturnValue("visible");
    await act(async () => document.dispatchEvent(new Event("visibilitychange")));
    expect(mock.summary).toHaveBeenCalledTimes(2);
    hook.unmount();
  });
});
