flyway.locations=filesystem:clickhouse_migrations/sql
flyway.jarDirs=clickhouse_migrations/drivers
flyway.table=flyway_schema_history
flyway.cleanDisabled=true
flyway.validateMigrationNaming=true
flyway.failOnMissingLocations=true
