"""Mechanical TypeScript generation from the backend contract catalog. No deps/IO services."""
import argparse
import json
from pathlib import Path
import re

from src.biz.schemas.wealth.market.trading_assistant.schema_catalog import json_schema_bundle

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / "wealth/src/features/trading-assistant/api/generatedContracts.ts"


def identifier(name):
    result = re.sub(r"[^A-Za-z0-9_$]", "_", name)
    if not result or result[0].isdigit():
        raise ValueError(f"Unsupported schema identifier: {name}")
    return result


def ts_type(schema):
    if "$ref" in schema:
        return identifier(schema["$ref"].removeprefix("#/$defs/"))
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in schema["enum"])
    for union in ("anyOf", "oneOf"):
        if union in schema:
            return "(" + " | ".join(ts_type(part) for part in schema[union]) + ")"
    kind = schema.get("type")
    if kind == "object":
        properties = schema.get("properties", {})
        required = schema.get("required", [])
        if schema.get("additionalProperties") is not False:
            raise ValueError("Open-ended objects are not supported by this contract generator")
        return "{ " + "; ".join(json.dumps(key) + ("" if key in required else "?") + ": " + ts_type(value)
            for key, value in properties.items()) + " }"
    if kind == "array":
        return "Array<" + ts_type(schema["items"]) + ">"
    if kind in ("string", "boolean", "null"):
        return kind
    if kind in ("integer", "number"):
        return "number"
    raise ValueError(f"Unsupported schema form: {schema}")


def generate():
    definitions = json_schema_bundle()["$defs"]
    names = [identifier(name) for name in definitions]
    if len(names) != len(set(names)):
        raise ValueError("Generated names collide")
    lines = ["// Generated by scripts/generate_trading_assistant_contracts.py. DO NOT EDIT."]
    for name, schema in sorted(definitions.items()):
        lines.append(f"export type {identifier(name)} = {ts_type(schema)};")
    lines.append("export interface Contracts {")
    lines.extend(f"  {json.dumps(name)}: {identifier(name)};" for name in sorted(definitions))
    lines.extend(["}", "export const contractSchemas = " + json.dumps(definitions, ensure_ascii=False,
        sort_keys=True, separators=(",", ":")) + ";", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text() != content:
            raise SystemExit("Trading-assistant generated contracts are stale")
    else:
        DESTINATION.parent.mkdir(parents=True, exist_ok=True)
        DESTINATION.write_text(content)


if __name__ == "__main__":
    main()
