from __future__ import annotations

# Deprecated compatibility shim:
# platform -> app/auth split phase 1 migrated main implementation to src.app.auth.constants.
from src.app.auth.constants import (
    ACCOUNT_STATE_ACTIVE,
    ACCOUNT_STATE_LOCKED,
    ACCOUNT_STATE_PENDING_VERIFICATION,
    ACCOUNT_STATE_SUSPENDED,
    AUTH_ACTION_RESET_PASSWORD,
    AUTH_ACTION_VERIFY_EMAIL,
    DEFAULT_PERMISSIONS,
    DEFAULT_ROLE_PERMISSIONS,
    DEFAULT_ROLES,
    ROLE_ADMIN,
    ROLE_ANALYST,
    ROLE_OPERATOR,
    ROLE_VIEWER,
)

__all__ = [
    "ACCOUNT_STATE_PENDING_VERIFICATION",
    "ACCOUNT_STATE_ACTIVE",
    "ACCOUNT_STATE_SUSPENDED",
    "ACCOUNT_STATE_LOCKED",
    "AUTH_ACTION_VERIFY_EMAIL",
    "AUTH_ACTION_RESET_PASSWORD",
    "ROLE_ADMIN",
    "ROLE_OPERATOR",
    "ROLE_ANALYST",
    "ROLE_VIEWER",
    "DEFAULT_ROLES",
    "DEFAULT_PERMISSIONS",
    "DEFAULT_ROLE_PERMISSIONS",
]
